### ISSUE TITLE
No ```colik.hpp```

### ISSUE THREAD

**Issue by sdwfrost** [emvolz-phylodynamics/phydynR#1]
phydynR fails to compile, there isn't a `colik.hpp`, which is included in [phylo.source.attribution.cpp](https://github.com/emvolz-phylodynamics/phydynR/blob/master/src/phylo.source.attribution.cpp#L8)

**Comment by emvolz** [comment]
Thanks for noticing! It has been added now, although it is actually not
being used yet.

Erik M Volz

Department of Infectious Disease Epidemiology
Imperial College London
e.volz@imperial.ac.uk
http://www.erikvolz.info
