### ISSUE TITLE
Failed to install 'phydynR' from GitHub?

### ISSUE THREAD

**Issue by liamxg** [emvolz-phylodynamics/phydynR#10]
18 warnings generated.
clang++ -arch x86_64 -std=gnu++17 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/BH/include' -I/opt/R/x86_64/include    -fPIC  -falign-functions=64 -Wall -g -O2  -c treeSimulatorCpp3.cpp -o treeSimulatorCpp3.o
treeSimulatorCpp3.cpp:197:7: warning: unused variable 'k' [-Wunused-variable]
                int k; 
                    ^
treeSimulatorCpp3.cpp:351:12: warning: assigning field to itself [-Wself-assign-field]
                                for (u = u; u < (n + internalNodesAdded); u++){
                                       ^
treeSimulatorCpp3.cpp:13:21: warning: unused variable 'A_EPS' [-Wunused-const-variable]
static const double A_EPS = 0.00;
                    ^
treeSimulatorCpp3.cpp:14:21: warning: unused variable 'Y_EPS' [-Wunused-const-variable]
static const double Y_EPS = 1.E-12;
                    ^
4 warnings generated.
clang++ -arch x86_64 -std=gnu++17 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/opt/R/x86_64/lib -o phydynR.so RcppExports.o colikModular0.o dAL0.o dPikL0.o dPikL1.o dQALarma0.o dQfwd.o phylo.source.attribution.o psa2.o solveQALboost0.o solveQALboost1.o treeSimulatorCpp2.o treeSimulatorCpp3.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/opt/gfortran/lib/gcc/x86_64-apple-darwin20.0/12.2.0 -L/opt/gfortran/lib -lgfortran -lquadmath -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: directory not found for option '-L/opt/gfortran/lib/gcc/x86_64-apple-darwin20.0/12.2.0'
ld: warning: directory not found for option '-L/opt/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [phydynR.so] Error 1
ERROR: compilation failed for package ‘phydynR’

**Comment by thednainus** [comment]
Hello, 
Try to use `devtools::install_github("emvolz-phylodynamics/phydynR", force = TRUE)`

**Comment by LiXingguangBrandonStark** [comment]
@thednainus thanks, still have error.
> devtools::install_github("emvolz-phylodynamics/phydynR", force = TRUE)
Using github PAT from envvar GITHUB_PAT
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 401.
  Bad credentials

  Rate limit remaining: 59/60
  Rate limit reset at: 2022-05-10 14:49:43 UTC

**Comment by thednainus** [comment]
Do you have these packages installed? `ape`, `deSolve`, `BH`, `inline`, `Rcpp`, `RcppArmadillo`.

**Comment by LiXingguangBrandonStark** [comment]
<img width="566" alt="image" src="https://user-images.githubusercontent.com/46078579/167648989-52cbe405-2e53-4e6c-bacc-6d5ea5d924c1.png">

**Comment by LiXingguangBrandonStark** [comment]
> devtools::install_github("emvolz-phylodynamics/phydynR", force = TRUE) Downloading GitHub repo emvolz-phylodynamics/phydynR@HEAD ✔  checking for file ‘/tmp/RtmpbxVa5u/remotes3c9445d3ad0/emvolz-phylodynamics-phydynR-7a69ece/DESCRIPTION’ ... ─  preparing ‘phydynR’: ✔  checking DESCRIPTION meta-information ─  cleaning src ─  installing the package to process help pages          ----------------------------------- ─  installing *source* package ‘phydynR’ ...    ** using staged installation    ** libs    g++ -std=gnu++11 -I"/opt/R/4.0.5/lib/R/include" -DNDEBUG  -I'/home/rstudio-user/R/x86_64-pc-linux-gnu-library/4.0/Rcpp/include' -I'/home/rstudio-user/R/x86_64-pc-linux-gnu-library/4.0/RcppArmadillo/include' -I'/home/rstudio-user/R/x86_64-pc-linux-gnu-library/4.0/BH/include' -I/usr/local/include   -fpic  -g -O2  -Wall -pedantic -fdiagnostics-color=always -c RcppExports.cpp -o RcppExports.o    g++:fatal error: ignal terminated program cc1plus    compilation terminated.    make: *** [/opt/R/4.0.5/lib/R/etc/Makeconf:181: RcppExports.o] Error 1    ERROR: compilation failed for package ‘phydynR’ ─  removing ‘/tmp/RtmpX2lGPx/Rinst44e12daa01b/phydynR’          -----------------------------------    ERROR: package installation failed Error: Failed to install 'phydynR' from GitHub:   System command 'R' failed, exit status: 1, stdout & stderr were printed
--
 
> | >
>

**Comment by thednainus** [comment]
I don't know whether this is your problem. But I found that this fatal error with g++ seems to be a memory problem (see [here](https://stackoverflow.com/questions/66967848/g-fatal-error-killed-signal-terminated-program-cc1plus-when-trying-to-install) for an example). If it still does not work, try to download the package to your computer and build the package with Rstudio, for example.

**Comment by LiXingguangBrandonStark** [comment]
thanks for your help, could you tell me how to install package  with Rstudio, thanks.

**Comment by LiXingguangBrandonStark** [comment]
<img width="977" alt="image" src="https://user-images.githubusercontent.com/46078579/168520840-4aceea8a-38aa-44f0-a046-399b551beee2.png">
